### ISSUE TITLE
Wildcard in black/white list filters

### ISSUE THREAD

**Issue by eddiejaoude** [henrikbjorn/PhpSpecCodeCoverageExtension#36]

**Comment by henrikbjorn** [comment]
If this is not already supported by the CodeCoverage library, then it is not gonna happen.

**Comment by eddiejaoude** [comment]
> If this is not already supported by the CodeCoverage library, then it is not gonna happen

You are not accepting **PR**s then!? ... Thats the spirit :cry:

**Comment by henrikbjorn** [comment]
I am accepting PRs, but if the library we use for Code Coverage does not support this in its own whitelist / blacklist feature, then it wont make sense here.
