### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by jtallant** [henrikbjorn/PhpSpecCodeCoverageExtension#38]
I get segfault errors about 30% of the time I run this.

Adding a custom bootstrap for phpspec and called `gc_disable()` seems to fix it.

Should this be built in or is there some other solution? Am I the only one getting the segfault?

**Comment by henrikbjorn** [comment]
What kind of environment are you using? php version, xdebug version, phpspec version etc.

**Comment by jtallant** [comment]
PHP Version 5.6.6
Xdebug v2.3.1
phpspec 2.2.2

![phpinfo](https://cloud.githubusercontent.com/assets/857110/10790732/05b689b2-7d53-11e5-8367-e131fda57d21.png)

**Comment by jtallant** [comment]
upgraded to php 5.6.9 and the segfault stopped
