### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by Sam-Burns** [henrikbjorn/PhpSpecCodeCoverageExtension#40]
Hi there - thanks for the awesome extension :-)

Now that PHPSpec 2.4.0 is stable and works in PHP 7, do you think you could maybe go back to supporting the new language version?  A tagged release with [this commit](https://github.com/henrikbjorn/PhpSpecCodeCoverageExtension/commit/e87de620c3fd67b431f4b7dbe03e1170ac1fa0ad) reverted would be great.

Thanks!

**Comment by henrikbjorn** [comment]
Hey @Sam-Burns there is a 2.0.0 release with support for php 7
