### ISSUE TITLE
PHP 5.5.x compatibility

### ISSUE THREAD

**Issue by gabiudrescu** [henrikbjorn/PhpSpecCodeCoverageExtension#42]
I see there is a requirement of 5.6.x, 7 or higher for this package, but things seem to run pretty smooth on 5.5.9 pretty well.

Given that Ubuntu 14.04 still ships by default with this and its the only LTE version Ubuntu currently provides, is there such a big burden to add 5.5 support for this extension?

The other chance of using this extension is to fork it myself and modify the composer.json, but I wouldn't like to take credit for that.

**Comment by henrikbjorn** [comment]
feel free to make a PR

**Comment by gabiudrescu** [comment]
pls check #43

**Comment by DavidGarciaCat** [comment]
Given PR #43 has been merged, I suggest to close this Issue.

Cheers,

**Comment by gabiudrescu** [comment]
shouldn't there be a tag for this? ^2.0 still goes to 2.0.1 which does not include my PR.

**Comment by henrikbjorn** [comment]
Well tagging doesn't happen automatically, and i just merged the PR from my phone. I have created a new release, just for you, have fun.
