### ISSUE TITLE
Skip an specific path

### ISSUE THREAD

**Issue by DavidGarciaCat** [henrikbjorn/PhpSpecCodeCoverageExtension#44]
Hey there,

I would like to know if there is any way to set up the config file to skip an specific directory.

I am working on several Symfony projects, and most of them have many Bundles, so this validator returns all Dependency Injection directories are not covered by my tests (just an example).

Could you help me please?

Thanks,

**Comment by henrikbjorn** [comment]
https://github.com/henrikbjorn/PhpSpecCodeCoverageExtension#configuration-options

> whitelist takes an array of directories to whitelist (default: lib, src).
> whitelist_files takes an array of files to whitelist (default: none).

**Comment by DavidGarciaCat** [comment]
:+1: 

Here I needed `blacklist` instead of `whitelist` - I suggest to add this documentation.

Thanks,
