### ISSUE TITLE
"Extension class `0` does not exist"

### ISSUE THREAD

**Issue by danmichaelo** [henrikbjorn/PhpSpecCodeCoverageExtension#58]
Not sure if this is an issue with PhpSpecCodeCoverageExtension or some dependency, but I report it here anyways.

    phpdbg -qrr vendor/bin/phpspec run

throws `[RuntimeException] Extension class `0` does not exist.` only if I enable the CodeCoverageExtension.

See [git repo for minimal example](https://github.com/danmichaelo/phpdbg-phpspec-test)

**Comment by danmichaelo** [comment]
I was wrong about phpdbg, seems like I get the same error both with and without it:

https://travis-ci.org/danmichaelo/phpdbg-phpspec-test/builds/151349747

Without the CodeCoverageExtension it works, however:

https://travis-ci.org/danmichaelo/phpdbg-phpspec-test/builds/151349361

Perhaps it doesn't like PSR-4?

**Comment by danmichaelo** [comment]
Hm, now I can't get it working with php 5.6 either! https://travis-ci.org/danmichaelo/phpdbg-phpspec-test/jobs/151460103

Perhaps I'm just messing something up?

**Comment by henrikbjorn** [comment]
Seems something is messed up. Does it work locally ?

**Comment by danmichaelo** [comment]
Nope. Turned out to be an error in the phpspec.yml . Embarassing, but I was using

```yml
extensions:
  - PhpSpecCodeCoverage\CodeCoverageExtension
```

instead of

```yml
extensions:
  PhpSpecCodeCoverage\CodeCoverageExtension:
```

I might have picked up the syntax from http://www.phpspec.net/en/stable/cookbook/extensions.html or similar, which is perhaps outdated.
