### ISSUE TITLE
Code Coverage takes a long time - how do I run w/o code coverage whilst developing tests?

### ISSUE THREAD

**Issue by angelsk** [henrikbjorn/PhpSpecCodeCoverageExtension#59]
- I'd like to have phpspec run w/o code coverage whilst in the midst of developing stuff
- I'd like to run html coverage on my local dev
- I'd like to run clover coverage on Jenkins

Are there profiles like with Behat?

Thank you.

**Comment by henrikbjorn** [comment]
You can leave the extension out of your config file. Not sure if phpspec allows you to run and specifying which config to use.
