### ISSUE TITLE
Thank You / Information regarding maintained fork (leanphp/phpspec-code-coverage)

### ISSUE THREAD

**Issue by ek9** [henrikbjorn/PhpSpecCodeCoverageExtension#63]
Hello,

I would like to say Thank You to the author and contributors of this extension. This extension has been proven to be useful when analyzing our codebase and we are thankful to all of the contributors.

For the reasons above we have decided to fork this package and backport any past stable release versions. This was done to make sure even older versions of the extension are accessible (all be it under new namespace), should this repository or the main package would be removed.

After veryfing that our backported versions are working correctly, we have published our package on packagist under `leanphp/phpspec-code-coverage` name and released our backported versions:

- [leanphp/phspec-code-coverage on Packagist](https://packagist.org/packages/leanphp/phpspec-code-coverage)
- [leanphp/phpspec-code-coverage on GitHub](https://github.com/leanphp/phpspec-code-coverage)

We have backported versions `1.0.1`, `2.1.0`, `3.0.1` and have released what was unreleased on `master` branch as `3.1.0`. We plan to keep backporting any changes from this repository (should it receive any PRs / updates) and are planning to do a PHP7+ focused release in the near future.

I decided to open an issue here to inform previous author, contributors or users regarding maintained fork and invite any contributors to send any PRs or share their ideas regarding the future of the work on our [github repository](https://github.com/leanphp/phpspec-code-coverage).

Please do not hesitate to contact me if you see any problems with the fork and Thank You again for Your open-source contributions!

Feel free to close this issue as approriate.

Regards,
ek9

**Comment by henrikbjorn** [comment]
Hey, cool you are doing a maintained fork. Feel free to open a PR with information about it for the readme.
